services:
  post-service:
    #    path to dockerfile
#    build: ./post-service
    image: epamromakotov/k8s-post-service:v1
    container_name: post-service
    ports:
      - 8082:8080
    environment:
      #      - POSTGRES_DB=${POSTGRES_DB}
      #      - POST_DB_PORT=${POST_DB_PORT}
      - POST_DB_URL=jdbc:postgresql://post-db:5432/${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - USER_SERVICE_LOCATION=http://user-service:8080/users/
    depends_on:
      - post-db
  #    restart: always

  post-db:
    image: postgres
    container_name: post-db
    volumes:
      - post-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POST_DB_PORT}:5432
    restart: always
# had service name 'user_service' but tomcat does not allow domain name to have  underscore'_', so changed to '-'
  user-service:
    #    path to dockerfile
#    build: ./user-service
    image: epamromakotov/k8s-user-service:v1
    container_name: user-service_container_name
    ports:
      - 8081:8080
    environment:
      #      - POSTGRES_DB=${POSTGRES_DB}
      #      - USER_DB_PORT=${USER_DB_PORT}
      - USER_DB_URL=jdbc:postgresql://user-db:5432/${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - user-db
  #    restart: always

  user-db:
    image: postgres
    container_name: user-db_container_name
    volumes:
      - user-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${USER_DB_PORT}:5432
    restart: always

volumes:
  post-db-data:
  user-db-data:



