spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
            ddl-auto: create-drop
#      ddl-auto: update
  datasource:
    url: ${POST_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver

user:
  service:
    location: ${USER_SERVICE_LOCATION}
