apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app-deployment
  labels:
    app: user-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user-app-container
          image: epamromakotov/k8s-user-service:v1
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: db-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: db-password
            - name: USER_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: user-db-config
                  key: user-db-url
---
apiVersion: v1
kind: Service
metadata:
  name: user-app-service
spec:
  type: NodePort
  selector:
    app: user-app
  ports:
    - protocol: TCP
      #      8081?
      port: 8080
      targetPort: 8080
      nodePort: 30100