spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
            ddl-auto: create-drop
#      ddl-auto: update
  datasource:
    url: ${USER_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
